### PR TITLE
Improve table

### PR DESCRIPTION
**Pull request by unixfox**
This improves the comparison table.

### CODE REVIEW

**Comment by davidcollini** [comment]
Thank you for the pull request! There's one thing though,  I decided to remove the checkmark from Invidious' Sponsorblock feature, since the feature relies on an extension and isn't built into the website

I've changed a few things, but everything else in this request has been added

**Comment by unixfox** [comment]
That's fine. Do note that piped doesn't work on ancient browser, it doesn't support IE11: https://github.com/TeamPiped/Piped/blob/09b163a1b6bb7eccdfd109cac117972c039d8f19/vite.config.js#L19

And the player provided by piped doesn't work on IE: https://github.com/shaka-project/shaka-player#platform-and-browser-support-matrix

**Comment by davidcollini** [comment]
> That's fine. Do note that piped doesn't work on ancient browser, it doesn't support IE11: https://github.com/TeamPiped/Piped/blob/09b163a1b6bb7eccdfd109cac117972c039d8f19/vite.config.js#L19
> 
> And the player provided by piped doesn't work on IE: https://github.com/shaka-project/shaka-player#platform-and-browser-support-matrix

I'll check it out and work on a solution that makes everyone happy, thanks for the info

**Comment by unixfox** [comment]
I meant to say that because we especially made some effort to support IE11: https://github.com/iv-org/invidious/pull/3045

Most of the JS code is ES6 compatible so it works on a wide range of browsers: https://caniuse.com/es6

And people were able to use invidious on Nokia symbian devices: https://github.com/iv-org/invidious/issues/2055#issuecomment-913094083

And even old PlayStation

IMO the main use case for "ancient device and browser" is to tell the user that they can still watch youtube videos on a browser that is not supported anymore by the official youtube.com website.

**Comment by davidcollini** [comment]
@FireMasterK @unixfox 

In order to avoid confusion for new users, listing the older version of browsers where the site breaks would be the best solution

The browsers would be chromium, safari, Firefox and IE

There would also be an attached hyperlink to each browser version for documentation or a site that explains this

This seems like the best plan for this category, let me know if you have any issues or helpful information, thanks🤙

**Comment by davidcollini** [comment]
> I meant to say that because we especially made some effort to support IE11: https://github.com/iv-org/invidious/pull/3045
> 
> Most of the JS code is ES6 compatible so it works on a wide range of browsers: https://caniuse.com/es6
> 
> And people were able to use invidious on Nokia symbian devices: https://github.com/iv-org/invidious/issues/2055#issuecomment-913094083
> 
> And even old PlayStation
> 
> IMO the main use case for "ancient device and browser" is to tell the user that they can still watch youtube videos on a browser that is not supported anymore by the official youtube.com website.

I just saw this after posting my previous comment, I'm not entirely sure how we could label the categories to get that across to the user

**Comment by davidcollini** [comment]
I'll put a number showing how many browsers are supported instead of a checkmark

Also, is there there a thing in html where I can make it so when the user hovers over the number for this category they can see all the site's supported browsers?

**Comment by FireMasterK** [comment]
> That's fine. Do note that piped doesn't work on ancient browser, it doesn't support IE11: https://github.com/TeamPiped/Piped/blob/09b163a1b6bb7eccdfd109cac117972c039d8f19/vite.config.js#L19
> And the player provided by piped doesn't work on IE: https://github.com/shaka-project/shaka-player#platform-and-browser-support-matrix

That's fine, we don't target IE11 since Piped's goal is to support browsers that aren't abandoned, my goal in Piped is to target legacy browsers that people likely use normally, while it's perfectly viable to transpile to IE11-compatible code (and then just use a video element whenever shaka fails), that's not my goal. Piped should work fine on legacy browsers like Waterfox, Palemoon, and really old versions of popular browsers, but it may not work on abandoned browsers (such as IE).

I also want to add that, using such browsers and operating systems come with severe security limitation, as most of these browsers still use a really old/insecure TLS versions. There are plenty of reasons to not be using such browsers.

> In order to avoid confusion for new users, listing the older version of browsers where the site breaks would be the best solution
> 
> The browsers would be chromium, safari, Firefox and IE
> 
> There would also be an attached hyperlink to each browser version for documentation or a site that explains this
> 
> This seems like the best plan for this category, let me know if you have any issues or helpful information, thanks

That could work, alternatively, maybe a new category could be added titled "Supports abandoned/unconventional browsers", which Piped doesn't meet.

**Comment by davidcollini** [comment]
Everything should be fully represented by the chart now, thanks for all the help

**Pull request merged**
